version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: androidx.fragment:fragment-ktx
    versions:
    - 1.2.5
    - 1.3.0
    - 1.3.1
    - 1.3.2
  - dependency-name: androidx.lifecycle:lifecycle-viewmodel-ktx
    versions:
    - 2.2.0
    - 2.3.0
  - dependency-name: androidx.lifecycle:lifecycle-livedata-ktx
    versions:
    - 2.2.0
    - 2.3.0
  - dependency-name: com.google.firebase:firebase-core
    versions:
    - 18.0.2
  - dependency-name: com.google.firebase:firebase-database
    versions:
    - 19.6.0
  - dependency-name: com.google.android.material:material
    versions:
    - 1.2.1
